repos:
  - repo: local
    hooks:
      - id: uv-lock
        name: uv lock
        entry: uv lock
        language: system
        files: ^(uv\.lock|pyproject\.toml|uv\.toml)$
        pass_filenames: false

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix --force-exclude --config pyproject.toml
        language: system
        types_or: [python, pyi]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --config pyproject.toml
        language: system
        types_or: [python, pyi, markdown]

      - id: ty-check
        name: ty check
        entry: uv run ty check --output-format concise --no-progress .
        language: system
        types_or: [python, pyi]
        pass_filenames: false
